#Workshop0

In [ ]:

# Task 1: Unit Conversion Program

def convert_units():
    """
    Converts between different units of measurement.

    Conversion Types:
    1. Length (meters <-> feet)
    2. Weight (kg <-> pounds)
    3. Volume (liters <-> gallons)

    Returns:
        float: Converted value
    """

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter choice (1/2/3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = int(input("Enter option: "))

            if sub_choice == 1:
                result = value * 3.28084
                print(f"{value} meters = {result} feet")
                return result
            elif sub_choice == 2:
                result = value / 3.28084
                print(f"{value} feet = {result} meters")
                return result

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Enter option: "))

            if sub_choice == 1:
                result = value * 2.20462
                print(f"{value} kg = {result} lbs")
                return result
            elif sub_choice == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result} kg")
                return result

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Enter option: "))

            if sub_choice == 1:
                result = value * 0.264172
                print(f"{value} L = {result} gal")
                return result
            elif sub_choice == 2:
                result = value / 0.264172
                print(f"{value} gal = {result} L")
                return result
        else:
            print("Invalid conversion type.")
            return None

    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return None

# Run
convert_units()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 1
Enter value to convert: 1
1. Meters to Feet
2. Feet to Meters
Enter option: 2
1.0 feet = 0.3047999902464003 meters


0.3047999902464003

Task2


In [ ]:

# Task 2: Mathematical Operations


def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """Returns the maximum value in a list."""
    return max(numbers)

def find_minimum(numbers):
    """Returns the minimum value in a list."""
    return min(numbers)


def math_operations():
    try:
        nums = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in nums.split()]

        if len(numbers) == 0:
            print("List is empty.")
            return

        print("Choose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter choice: "))

        if choice == 1:
            print("Sum =", calculate_sum(numbers))
        elif choice == 2:
            print("Average =", calculate_average(numbers))
        elif choice == 3:
            print("Maximum =", find_maximum(numbers))
        elif choice == 4:
            print("Minimum =", find_minimum(numbers))
        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input.")

# Run
math_operations()

Enter numbers separated by spaces: 1 2
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Sum = 3.0


Task3


In [ ]:
matrix= [
    [1 , 2 , 3],
    [4 , 5 , 6]
]
print(matrix)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
# 4.2 Exercise on List Manipulation
# 1. Extract Every Other Element
def extract_every_other(lst):
    """Returns every other element starting from first."""
    return lst[::2]


# 2. Get Sublist (inclusive)
def get_sublist(lst, start, end):
    """Returns sublist from start to end (inclusive)."""
    return lst[start:end+1]


# 3. Reverse List
def reverse_list(lst):
    """Returns reversed list using slicing."""
    return lst[::-1]


# 4. Remove First and Last
def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]


# 5. Get First n Elements
def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]


# 6. Get Last n Elements
def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]


# 7. Reverse Skip
def reverse_skip(lst):
    """Returns every second element starting from second-last, backwards."""
    return lst[-2::-2]

Task4


In [ ]:
import numpy as np


In [ ]:
#  4.3 Exercise on Nested List
# 1. Flatten Nested List (Simple)
def flatten(lst):
    """Flattens one level nested list."""
    result = []
    for item in lst:
        for element in item:
            result.append(element)
    return result
# 2. Access Nested Element
def access_nested_element(lst, indices):
    """
    Returns element from nested list using list of indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element
# 3. Sum Nested (Any Depth)
def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total
# 4. Remove Element from Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from nested list."""
    new_list = []
    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))
        elif item != elem:
            new_list.append(item)
    return new_list
# 5. Find Maximum in Nested List
def find_max(lst):
    """Finds maximum element in nested list."""
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value
# 6. Count Occurrences in Nested List
def count_occurrences(lst, elem):
    """Counts occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count
# 7. Deep Flatten (Any Depth)
def deep_flatten(lst):
    """Flattens deeply nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result
# 8. Average of Nested List
def average_nested(lst):
    """Returns average of nested list elements."""
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)

Task5

In [ ]:
# array creation
# 1. Empty array 2x2
arr1 = np.empty((2,2))
print("Empty 2x2 array:\n", arr1)

# 2. All ones array 4x2
arr2 = np.ones((4,2))
print("\nAll ones 4x2:\n", arr2)

# 3. Array filled with specific value
arr3 = np.full((3,3), 7)
print("\nFull array (3x3 filled with 7):\n", arr3)

# 4. Zeros like existing array
arr4 = np.zeros_like(arr2)
print("\nZeros like arr2:\n", arr4)

# 5. Ones like existing array
arr5 = np.ones_like(arr2)
print("\nOnes like arr2:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\nConverted list to array:\n", arr6)

Empty 2x2 array:
 [[3.79298738e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]

All ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like arr2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Converted list to array:
 [1 2 3 4]


In [ ]:
# Array multiplication
# 1. Values from 10 to 49
a = np.arange(10,50)
print("Array 10 to 49:\n", a)

# 2. 3x3 matrix from 0 to 8
b = np.arange(9).reshape(3,3)
print("\n3x3 matrix 0-8:\n", b)

# 3. 3x3 identity matrix
c = np.eye(3)
print("\nIdentity matrix:\n", c)

# 4. Random array size 30 and mean
d = np.random.random(30)
print("\nMean:", d.mean())

# 5. 10x10 random array min & max
e = np.random.random((10,10))
print("\nMinimum:", e.min())
print("Maximum:", e.max())

# 6. Zero array size 10 and replace 5th element
f = np.zeros(10)
f[4] = 1
print("\nReplace 5th element:\n", f)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed:", arr[::-1])

# 8. 2D array with 1 border and 0 inside
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print("\nBorder 1 inside 0:\n", g)

# 9. 8x8 checkerboard
h = np.zeros((8,8))
h[1::2, ::2] = 1
h[::2, 1::2] = 1
print("\nCheckerboard:\n", h)

Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.5023030383579592

Minimum: 0.0014320548843538283
Maximum: 0.9934217485248412

Replace 5th element:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("Addition:\n", x + y)

# 2. Subtract
print("\nSubtraction:\n", x - y)

# 3. Multiply by integer
print("\nMultiply x by 3:\n", x * 3)

# 4. Square
print("\nSquare of x:\n", x**2)

# 5. Dot products
print("\nDot v and w:", np.dot(v,w))
print("Dot x and v:", np.dot(x,v))
print("Dot x and y:\n", np.dot(x,y))

# 6. Concatenate
print("\nConcatenate x and y (row):\n", np.vstack((x,y)))
print("\nConcatenate v and w (column):\n", np.vstack((v,w)))

# 7. Concatenate x and v
# This will give error because dimensions do not match
# x is 2D (2x2) and v is 1D (2,)
# They must have same dimensions

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot v and w: 219
Dot x and v: [29 77]
Dot x and y:
 [[19 22]
 [50 58]]

Concatenate x and y (row):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w (column):
 [[ 9 10]
 [11 12]]


In [ ]:
#Matrix operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1:\n", np.dot(A, A_inv))

# 2. Prove AB != BA
print("\nAB:\n", np.dot(A,B))
print("\nBA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
# 10.2 Experiment: How Fast is NumPy?
import time

size = 1000000

# Create Python lists
list1 = list(range(size))
list2 = list(range(size))

# Create NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

# 1. Element-wise Addition
start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("Python List Addition Time:", time.time() - start)

start = time.time()
result = arr1 + arr2
print("NumPy Addition Time:", time.time() - start)


# 2. Element-wise Multiplication
start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("Python List Multiplication Time:", time.time() - start)

start = time.time()
result = arr1 * arr2
print("NumPy Multiplication Time:", time.time() - start)


# 3. Dot Product
start = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
print("Python Dot Product Time:", time.time() - start)

start = time.time()
dot = np.dot(arr1, arr2)
print("NumPy Dot Product Time:", time.time() - start)


# 4. Matrix Multiplication (1000x1000)
m1 = np.random.random((1000,1000))
m2 = np.random.random((1000,1000))

start = time.time()
result = np.dot(m1, m2)
print("NumPy Matrix Multiplication Time:", time.time() - start)

Python List Addition Time: 0.11028695106506348
NumPy Addition Time: 0.017872333526611328
Python List Multiplication Time: 0.12009739875793457
NumPy Multiplication Time: 0.016416072845458984
Python Dot Product Time: 0.10515809059143066
NumPy Dot Product Time: 0.0021238327026367188
NumPy Matrix Multiplication Time: 0.059999704360961914
